// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rmvgldjhangoxjzgbbyd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJtdmdsZGpoYW5nb3hqemdiYnlkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzMzMxNDksImV4cCI6MjA2ODkwOTE0OX0.EIz-kP2e9gTEpyQ3qUQbvt5uSKV8RsTivQ11aVzRtFg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});